name: JobMate Facebook Bot

on:
  schedule:
    - cron: '15 1 * * *'   # 7am Nepal (UTC 1:15)
    - cron: '15 4 * * *'   # 10am Nepal
    - cron: '15 6 * * *'   # 12pm Nepal
    - cron: '15 8 * * *'   # 2pm Nepal
    - cron: '15 10 * * *'  # 4pm Nepal
    - cron: '15 12 * * *'  # 6pm Nepal
    - cron: '15 14 * * *'  # 8pm Nepal
    - cron: '15 16 * * *'  # 10pm Nepal
  workflow_dispatch:

jobs:
  post-jobs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install Playwright
        run: npx playwright install chromium --with-deps
        
      - name: Run bot
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          GITHUB_TOKEN_GIST: ${{ secrets.GIST_TOKEN  }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: node index.js